spring:
  config:
    activate:
      on-profile: local
  security:
    jwt:
      header: Authorization
      secret: SnVzdGluU2VvLVRlYW9yZGVyc2VydmljZS1TcHJpbmdCb290LUpXVC1TZWNyZXQtVG9rZW4=
      token_expiration_time: 864000
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:teaorderdb;
    hikari:
      data-source-class-name:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: false
    database: h2
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: seojeonghyeon0630@gmail.com
    password: pluctpniwkrppucf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          enable: true
          starttls:
            enable: true

server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: on_param
    include-stacktrace: on_param
    include-message: on_param
    include-exception: true
  port: 8080
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
app:
  host: http://${HOST:localhost}:${server.port}