spring:
  config:
    activate:
      on-profile: stg
  security:
    jwt:
      header: Authorization
      secret: SnVzdGluU2VvLVRlYW9yZGVyc2VydmljZS1TcHJpbmdCb290LUpXVC1TZWNyZXQtVG9rZW4=
      token_expiration_time: 864000
  datasource:
    driver-class-name: org.postgresql.Driver
    username: api_user
    password: '00000000'
    url: jdbc:postgresql://postgres.${NAMESPACE}:5432/teaorderdb
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      pool-name: hikariPool
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: seojeonghyeon0630@gmail.com
    password: qwcwnodicfohbtnf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          enable: true
          starttls:
            enable: true

server:
  error:
    whitelabel:
      enabled: false
  port: 8080
logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type: info
  file:
    path: /output/${HOSTNAME}
app:
  host: http://${HOST:localhost}:${server.port}
management:
  endpoint:
    health:
      enabled: true
      show-details: always